spring:
  profiles:
    active: one
---
spring:
  profiles: one
server:
  port: 8888
eureka:
  client:
    register-with-eureka: false  # 不向eureka注册
    service-url:
      defaultZone: http://eureke7000.com:7000/eureka/,http://eureke7001.com:7001/eureka/,http://eureke7002.com:7002/eureka/
feign:
  hystrix:
    enabled: true # 开启降级

